const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        //version: "1.0.0",
        title: "API - Modulo de Soporte - Getión de Productos y Versiones",
        //description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "modulo-soporte-productos-psa.herokuapp.com",
    basePath: "/",
    schemes: ['https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    definitions: {
        Licence: {
            id: 77,
            productId: 61,
            versionId: 4,
            clientId: 1,
            expirationDate: '2024-05-05T00:00:00.000+00:00',
            state: 'ACTIVE'
        },
        Product: {
            id: 61,
            name: 'PSA Business Analytics'
        },
        Version: {
            id: 4,
            name: 'PSA Business Analytics',
            state: 'ACTIVE',
            productId: 61
        },
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app')           // Your project's root file
})